### ISSUE TITLE
Unable to load plugin in latest build

### ISSUE THREAD

**Issue by AdminHcat** [4drian3d/LogFilter#34]
https://github.com/PaperMC/Paper/pull/9160
https://github.com/PaperMC/Paper/pull/9267
Log:
```
( 7:07:10.71) Minecraft started.
WARNING: Using incubator modules: jdk.incubator.vector
Starting org.bukkit.craftbukkit.Main
System Info: Java 17 (Java HotSpot(TM) 64-Bit Server VM 17.0.7+8-LTS-224) Host: Windows 10 10.0 (amd64)
Loading libraries, please wait...
[07:07:22 INFO]: [SparkProviderSource] Purpur: Using user-provided spark plugin instead of our own.
[07:07:25 ERROR]: [BootstrapProviderStorage] Failed to run bootstrapper for plugins\LogFilter-Paper-3.0.5.jar. This plugin will not be loaded.
java.lang.AbstractMethodError: Receiver class me.adrianed.logfilter.paper.LogBootstrap does not define or inherit an implementation of the resolved method 'abstract void bootstrap(io.papermc.paper.plugin.bootstrap.BootstrapContext)' of interface io.papermc.paper.plugin.bootstrap.PluginBootstrap.
        at io.papermc.paper.plugin.storage.BootstrapProviderStorage$1.load(BootstrapProviderStorage.java:34) ~[purpur-1.19.4.jar:git-Purpur-1984]
        at io.papermc.paper.plugin.storage.BootstrapProviderStorage$1.load(BootstrapProviderStorage.java:22) ~[purpur-1.19.4.jar:git-Purpur-1984]
        at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:117) ~[purpur-1.19.4.jar:git-Purpur-1984]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[purpur-1.19.4.jar:git-Purpur-1984]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[purpur-1.19.4.jar:git-Purpur-1984]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enterBootstrappers(LaunchEntryPointHandler.java:26) ~[purpur-1.19.4.jar:git-Purpur-1984]
        at net.minecraft.server.Bootstrap.lambda$bootStrap$0(Bootstrap.java:75) ~[?:?]
        at net.minecraft.core.registries.BuiltInRegistries.bootStrap(BuiltInRegistries.java:321) ~[purpur-1.19.4.jar:git-Purpur-1984]
        at net.minecraft.server.Bootstrap.bootStrap(Bootstrap.java:73) ~[?:?]
        at net.minecraft.server.Main.main(Main.java:127) ~[purpur-1.19.4.jar:git-Purpur-1984]
        at org.bukkit.craftbukkit.Main.main(Main.java:330) ~[purpur-1.19.4.jar:git-Purpur-1984]
        at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42) ~[app:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]



```

**Comment by 4drian3d** [comment]
Fixed in https://modrinth.com/plugin/logfilter/version/3.0.6
