### ISSUE TITLE
Paper-specific builds struggling on paper

### ISSUE THREAD

**Issue by BornToDoStuff** [4drian3d/LogFilter#37]
I am having trouble with both the paper builds 3.0.5 and 3.0.6 on each of paper 1.20 and paper 1.20.1, interestingly it has an error, says it loads despite the error, and then (expectedly) refuses to work.

This error did not occur with the paper build 3.0.5 on 1.19.4, and does not occur with the bukkit build of 3.0.5 on 1.20.1, so while it does work if I use the bukkit build I thought I should bring it up.

## Error of the build 3.0.5 on 1.20.1
`[19.06 22:16:38] [Server] [ERROR] [BootstrapProviderStorage] Failed to run bootstrapper for plugins/LogFilter-Paper-3.0.5.jar. This plugin will not be loaded.
[19.06 22:16:38] [Server] java.lang.AbstractMethodErrorReceiver class me.adrianed.logfilter.paper.LogBootstrap does not define or inherit an implementation of the resolved method 'abstract void bootstrap(io.papermc.paper.plugin.bootstrap.BootstrapContext)' of interface io.papermc.paper.plugin.bootstrap.PluginBootstrap.
[19.06 22:16:38] [Server] 	at io.papermc.paper.plugin.storage.BootstrapProviderStorage$1.load(BootstrapProviderStorage.java:34) ~[paper-1.20.1.jar:git-Paper-43]
[19.06 22:16:38] [Server] 	at io.papermc.paper.plugin.storage.BootstrapProviderStorage$1.load(BootstrapProviderStorage.java:22) ~[paper-1.20.1.jar:git-Paper-43]
[19.06 22:16:38] [Server] 	at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:117) ~[paper-1.20.1.jar:git-Paper-43]
[19.06 22:16:38] [Server] 	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[paper-1.20.1.jar:git-Paper-43]
[19.06 22:16:38] [Server] 	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[paper-1.20.1.jar:git-Paper-43]
[19.06 22:16:38] [Server] 	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enterBootstrappers(LaunchEntryPointHandler.java:26) ~[paper-1.20.1.jar:git-Paper-43]
[19.06 22:16:38] [Server] 	at net.minecraft.server.Bootstrap.lambda$bootStrap$0(Bootstrap.java:82) ~[?:?]
[19.06 22:16:38] [Server] 	at net.minecraft.core.registries.BuiltInRegistries.bootStrap(BuiltInRegistries.java:328) ~[paper-1.20.1.jar:git-Paper-43]
[19.06 22:16:38] [Server] 	at net.minecraft.server.Bootstrap.bootStrap(Bootstrap.java:80) ~[?:?]
[19.06 22:16:38] [Server] 	at net.minecraft.server.Main.main(Main.java:127) ~[paper-1.20.1.jar:git-Paper-43]
[19.06 22:16:38] [Server] 	at org.bukkit.craftbukkit.Main.main(Main.java:316) ~[paper-1.20.1.jar:git-Paper-43]
[19.06 22:16:38] [Server] 	at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42) ~[app:?]
[19.06 22:16:38] [Server] 	at java.lang.Thread.run(Thread.java:833) ~[?:?]`

## Error of the build 3.0.6 on 1.20.1
`[19.06 22:09:27] [Server] [ERROR] [LogFilter] Error initializing plugin 'LogFilter-Paper-3.0.6.jar' in folder 'plugins' (Is it up to date?)
[19.06 22:09:27] [Server] java.lang.NoClassDefFoundErrorme/adrianed/logfilter/common/configuration/Loader
[19.06 22:09:27] [Server] 	at me.adrianed.logfilter.paper.LogFilterPaper.onLoad(LogFilterPaper.java:27) ~[LogFilter-Paper-3.0.6.jar:?]
[19.06 22:09:27] [Server] 	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[paper-1.20.1.jar:git-Paper-43]
[19.06 22:09:27] [Server] 	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[paper-1.20.1.jar:git-Paper-43]
[19.06 22:09:27] [Server] 	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:40) ~[paper-1.20.1.jar:git-Paper-43]
[19.06 22:09:27] [Server] 	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[paper-1.20.1.jar:git-Paper-43]
[19.06 22:09:27] [Server] 	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.loadPlugins(CraftServer.java:504) ~[paper-1.20.1.jar:git-Paper-43]
[19.06 22:09:27] [Server] 	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:273) ~[paper-1.20.1.jar:git-Paper-43]
[19.06 22:09:27] [Server] 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.20.1.jar:git-Paper-43]
[19.06 22:09:27] [Server] 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-43]
[19.06 22:09:27] [Server] 	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[19.06 22:09:27] [Server] Caused byjava.lang.ClassNotFoundException: me.adrianed.logfilter.common.configuration.Loader
[19.06 22:09:27] [Server] 	at io.papermc.paper.plugin.entrypoint.classloader.PaperPluginClassLoader.loadClass(PaperPluginClassLoader.java:142) ~[paper-1.20.1.jar:git-Paper-43]
[19.06 22:09:27] [Server] 	at io.papermc.paper.plugin.entrypoint.classloader.PaperPluginClassLoader.loadClass(PaperPluginClassLoader.java:103) ~[paper-1.20.1.jar:git-Paper-43]
[19.06 22:09:27] [Server] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
[19.06 22:09:27] [Server] 	... more`

**Comment by 4drian3d** [comment]
Fixed, please redownload the plugin from https://modrinth.com/plugin/logfilter/version/3.0.6
