### ISSUE TITLE
BungeeCord: NoClassDefFoundError (/LogManager)

### ISSUE THREAD

**Issue by RedstoneFuture** [4drian3d/LogFilter#72]
Using of [LogFilter 3.0.5 Bungee](https://modrinth.com/plugin/logfilter/version/DD0SZMfW) have no problems on Waterfall. But I get the following warning message on BungeeCord with the startup:

```
04:26:55 [WARNUNG] Exception encountered when loading plugin: LogFilter
java.lang.NoClassDefFoundError: org/apache/logging/log4j/LogManager
	at me.adrianed.logfilter.bungee.LogFilterBungee.onEnable(LogFilterBungee.java:18)
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:266)
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:298)
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67)
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.LogManager
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:103)
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 5 more
```

In addition, no Config folder is created on BungeeCord with the first startup.

Since Waterfall is no longer being developed, I would like to use BungeeCord on the production server for the time being and would be very happy if the plugin could still be used for this.

_Tested with BungeeCord version git:BungeeCord-Bootstrap:1.21-R0.1-SNAPSHOT:01a5f36:1873_

**Comment by 4drian3d** [comment]
The bungee module is discontinued and no longer supported, use Velocity
